/*
 * main.c -- minimal starter for the S9S08SG8E2MTJ (MC9S08SG8 family)
 *
 * Toggles PTA0 in a busy-wait loop. This is meant as a "does the chip
 * respond to a program I compiled myself" bring-up test, to be flashed
 * with pico-bdm (../../host, ../../firmware) rather than a real BDM pod.
 *
 * ADJUST PTAD/PTADD BIT NUMBERS to whatever pin you actually have an LED
 * (or a scope probe) wired to on your board -- PTA0 is just an example.
 *
 * Build in CodeWarrior for Microcontrollers 6.3: New Project -> Device
 * "MC9S08SG8" -> language C -> no PE (Processor Expert) needed for
 * something this simple. Replace the generated main.c with this file.
 * Build produces a .s19 under <project>/Debug or <project>/Release --
 * that's the file to feed into pico-bdm's Flash panel.
 */

#include <hidef.h>      /* for EnableInterrupts, disable via CodeWarrior */
#include "derivative.h" /* device-specific register/bit definitions, generated by CodeWarrior's device selection */

void delay(unsigned int loops) {
  while (loops--) {
    /* empty -- just burn cycles; not calibrated to a real time unit */
  }
}

void main(void) {
  /* Disable the watchdog (COP) for this simple test -- SOPT1 default has
   * COPE set on this family, so without this the chip resets itself
   * before you see anything happen. Comment this out and feed the
   * watchdog properly (or configure a longer timeout) once you're past
   * bring-up and writing real firmware. */
  SOPT1 = 0x00; /* SOPT1_COPE = 0 -- verify this matches your device's SOPT1 reset value/bit layout in the SG8/SG4 datasheet before relying on it */

  PTADD_PTADD0 = 1; /* PTA0 = output */

  for (;;) {
    PTAD_PTAD0 = 1; /* drive high */
    delay(20000);
    PTAD_PTAD0 = 0; /* drive low */
    delay(20000);
  }
}
