/*
 * main.c -- minimal starter for the S9S08SG8E2MTJ (MC9S08SG8 family)
 *
 * Toggles PTA0 in a busy-wait loop. This is meant as a "does the chip
 * respond to a program I compiled myself" bring-up test, to be flashed
 * with pico-bdm (../../host, ../../firmware) rather than a real BDM pod.
 *
 * ADJUST PTAD/PTADD BIT NUMBERS to whatever pin you actually have an LED
 * (or a scope probe) wired to on your board -- PTA0 is just an example.
 *
 * Build in CodeWarrior for Microcontrollers 6.3: New Project -> Device
 * "MC9S08SG8" -> language C -> no PE (Processor Expert) needed for
 * something this simple. Replace the generated main.c with this file.
 * Build produces a .s19 under <project>/Debug or <project>/Release --
 * that's the file to feed into pico-bdm's Flash panel.
 */

#include <hidef.h>      /* for EnableInterrupts, disable via CodeWarrior */
#include "derivative.h" /* device-specific register/bit definitions, generated by CodeWarrior's device selection */

void delay(unsigned int loops) {
  /* `volatile` is load-bearing, not decoration: the loop body is empty and
   * has no side effects, so without it an optimizing compiler is entitled
   * to delete the whole loop. CodeWarrior's default Debug build probably
   * wouldn't, but a Release build would -- and the pin would then toggle at
   * full bus speed with nothing visible, which looks exactly like "the chip
   * never ran my code" on first bring-up. */
  volatile unsigned int i = loops;
  while (i--) {
    /* empty -- just burn cycles; not calibrated to a real time unit */
  }
}

void main(void) {
  /* Disable the watchdog (COP) for this simple test.
   *
   * Verified against the MC9S08SG8 datasheet §5.7.3 (2026-09-11): the COP
   * on this family is controlled by a two-bit COPT field at SOPT1[7:6],
   * NOT by a COPE enable bit -- there is no COPE, BKGDPE or RSTPE bit in
   * SOPT1 on this part at all. COPT resets to 1:1, which is why SOPT1's
   * reset value is 0xC0 (COP enabled, longest timeout).
   *
   * Writing 0x00 therefore clears COPT to 0:0 = COP disabled, and -- since
   * there is no BKGDPE bit here to accidentally clear -- carries no risk of
   * disabling BDM access, which is what would make the chip unreachable by
   * pico-bdm. SOPT1 is a write-once register, so this must happen early.
   *
   * Once you're past bring-up, feed the COP properly or pick a longer
   * timeout via COPT instead of disabling it. */
  SOPT1 = 0x00; /* COPT = 0:0 -> COP watchdog off (reset value is 0xC0) */

  PTADD_PTADD0 = 1; /* PTA0 = output */

  for (;;) {
    PTAD_PTAD0 = 1; /* drive high */
    delay(20000);
    PTAD_PTAD0 = 0; /* drive low */
    delay(20000);
  }
}
